const express = require('express');
const router = express.Router();

router.use('/auth', require('./routesLogin'));          // /api/auth/...
router.use('/prueba', require('./prueba'));             // /api/prueba/...
router.use('/dashboard', require('./routesInicioUsuario')); // /api/dashboard/...
module.exports = router;
